// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using template_csharp_blog;

namespace template_csharp_blog.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("template_csharp_blog.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "MacAtack92",
                            Firstname = "Denzale",
                            Lastname = "McIntyre"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Stormyweather",
                            Firstname = "Storm",
                            Lastname = "Kendall"
                        },
                        new
                        {
                            Id = 3,
                            Email = "FiremanCannon",
                            Firstname = "Chris",
                            Lastname = "Cannon"
                        });
                });

            modelBuilder.Entity("template_csharp_blog.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Catergory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publishdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Catergory = "Sci-Fi",
                            Content = "Not only does he use his power for the need of others but he also inspires other as well",
                            Publishdate = "2-4-2020",
                            Title = "Why Mirio is the G.O.A.T"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Catergory = "Sports",
                            Content = "I just like Big Ben",
                            Publishdate = "9 - 18 - 2020",
                            Title = "Why the steelers rule"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Catergory = "Movies",
                            Content = "Andrew played his role of Peter Parker AND Spider-Man better than all the other actors",
                            Publishdate = "05 - 12 - 2020",
                            Title = "Andrew was the best Spiderman"
                        });
                });

            modelBuilder.Entity("template_csharp_blog.Models.Blog", b =>
                {
                    b.HasOne("template_csharp_blog.Models.Author", "Author")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("template_csharp_blog.Models.Author", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
